name: tick_to_do
description: Elegant and simple To Do app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: "2.0.0+8"

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animations: ^2.0.7
  bloc: ^8.1.3
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.1
  dartz: ^0.10.1
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_lints:
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  google_sign_in: ^6.0.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.0.18

dev_dependencies:
  build_runner: ^2.1.8
  flutter_native_splash:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter_native_splash:
  color: '#ffffff'
  image: images/logo.png
  color_dark: '#1a1a1a'
  image_dark: images/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
     - images/
  fonts:
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Light.ttf
          weight: 200